"use client";

import Link from "next/link";
import { useEffect, useMemo, useRef, useState } from "react";
import { ArrowRight, ArrowUpRight, CornerDownLeft, Search, X } from "lucide-react";
import { categories, tools, type CategoryId, type Tool } from "@/lib/tools";
import { ToolIcon } from "@/components/tool-icon";

function ToolCard({ tool }: { tool: Tool }) {
  return <Link href={`/tools/${tool.id}/`} className="tool-card group"><div className="flex items-start justify-between"><ToolIcon tool={tool} /><span className="font-mono text-[11px] tracking-widest text-muted-foreground">{tool.marker} / 05</span></div><div className="mt-auto pt-7"><span className="text-[11px] font-bold tracking-[.09em] text-muted-foreground">{tool.categoryLabel}</span><h3 className="mt-1 text-[19px] font-bold tracking-[-.04em]">{tool.title}</h3><div className="mt-2 flex items-center justify-between"><p className="text-[13px] text-muted-foreground">{tool.short}</p><ArrowUpRight size={19} className="text-muted-foreground transition-transform group-hover:-translate-y-1 group-hover:translate-x-1 group-hover:text-primary"/></div></div></Link>;
}

export function HomeHub() {
  const [query, setQuery] = useState("");
  const [category, setCategory] = useState<CategoryId>("all");
  const [focused, setFocused] = useState(false);
  const searchRef = useRef<HTMLInputElement>(null);
  useEffect(() => {
    const onKey = (event: KeyboardEvent) => {
      if (event.key === "/" && !(event.target instanceof HTMLInputElement) && !(event.target instanceof HTMLTextAreaElement)) { event.preventDefault(); searchRef.current?.focus(); }
      if (event.key === "Escape") { searchRef.current?.blur(); setFocused(false); }
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, []);
  const filtered = useMemo(() => tools.filter((tool) => (category === "all" || tool.category === category) && `${tool.title} ${tool.short} ${tool.description} ${tool.keywords.join(" ")}`.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase())), [category, query]);
  const suggestions = query.trim() ? tools.filter((tool) => `${tool.title} ${tool.keywords.join(" ")}`.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase())).slice(0, 4) : [];

  return <>
    <section className="container-wide pt-14 md:pt-22"><div className="grid items-center gap-10 lg:grid-cols-[1.08fr_.92fr] lg:gap-15"><div className="py-5"><div className="mb-7 flex items-center gap-3"><span className="h-2 w-2 rounded-full bg-[#8d81e8]"/><span className="eyebrow text-primary">PAISTAR / PERSONAL TOOLKIT</span></div><h1 className="display-heading">顺手的事，<br/><span className="text-[#6d62d7] dark:text-[#afa6ff]">现在就做。</span></h1><p className="mt-7 max-w-[490px] text-[15px] leading-[1.95] text-muted-foreground md:text-[17px]">从整理 JSON 到生成二维码，把常用的小工具放在一个安静、好用的地方。打开即用，内容只留在你的浏览器。</p><div className="mt-9 flex flex-wrap items-center gap-5"><a href="#find" className="inline-flex h-12 items-center gap-3 rounded-[13px] bg-primary px-5 text-[14px] font-semibold text-primary-foreground transition hover:-translate-y-0.5 hover:shadow-lg">探索工具 <ArrowRight size={17}/></a><span className="text-[12px] text-muted-foreground">05 个工具 · 无需注册 · 纯前端运行</span></div></div><div className="hero-board"><div className="absolute left-8 top-8 flex items-center gap-2"><span className="h-[7px] w-[7px] rounded-full bg-[#b7afea]"/><span className="eyebrow text-[#dad8fb]">WORKSPACE / 001</span></div><div className="absolute left-8 top-[92px] max-w-[280px]"><p className="text-[30px] font-semibold leading-[1.22] tracking-[-.06em] md:text-[34px]">让工具回到<br/>简单的样子。</p><p className="mt-4 max-w-[220px] text-[12px] leading-6 text-[#c9cce1]">清楚的入口、及时的反馈、刚刚好的细节。</p></div><div className="absolute bottom-7 left-8 right-8 z-10 flex items-end justify-between"><span className="font-mono text-[11px] text-[#e6e4fc]">YOUR IDEAS, IN MOTION.</span><div className="flex h-[100px] w-[100px] items-center justify-center rounded-[24px] border border-white/30 bg-white/13 shadow-2xl backdrop-blur-md"><span className="text-[56px] font-light leading-none text-white">✳</span></div></div><div className="absolute -right-8 top-[100px] h-[175px] w-[175px] rounded-full border border-white/20"/></div></div></section>
    <section id="find" className="container-wide scroll-mt-30 pt-19 md:pt-26"><div className="mb-6 flex flex-col gap-2 md:flex-row md:items-end md:justify-between"><div><p className="eyebrow text-primary">THE TOOL SHELF / 01</p><h2 className="section-heading mt-3">找到需要的那一个</h2></div><span className="text-[13px] text-muted-foreground">从关键词开始，或者按用途浏览。</span></div><div className="search-wrap"><Search size={20} className="pointer-events-none absolute left-5 top-[21px] z-10 text-muted-foreground"/><input id="global-search" ref={searchRef} value={query} onChange={(event) => setQuery(event.target.value)} onFocus={() => setFocused(true)} onBlur={() => window.setTimeout(() => setFocused(false), 120)} className="search-field" placeholder="搜索工具，比如 JSON、时间戳、二维码…" aria-label="搜索工具" autoComplete="off"/><span className="pointer-events-none absolute right-5 top-5 hidden rounded-md border border-border px-2 py-0.5 font-mono text-[11px] text-muted-foreground md:block">/</span>{query && <button type="button" onClick={() => { setQuery(""); searchRef.current?.focus(); }} className="icon-shell absolute right-3 top-3 md:right-13" aria-label="清空搜索"><X size={16}/></button>}{focused && suggestions.length > 0 && <div className="search-popover glass" role="listbox" aria-label="搜索建议">{suggestions.map((tool) => <Link role="option" aria-selected="false" key={tool.id} href={`/tools/${tool.id}/`}><span>{tool.title}<small className="ml-3 text-muted-foreground">{tool.categoryLabel}</small></span><CornerDownLeft size={14} className="text-muted-foreground"/></Link>)}</div>}</div><div className="mt-5 flex flex-wrap gap-2" aria-label="按分类筛选工具">{categories.map((item) => <button key={item.id} type="button" onClick={() => setCategory(item.id)} className={`chip-button ${category === item.id ? "selected" : ""}`} aria-pressed={category === item.id}>{item.label}<span className="opacity-65">{item.id === "all" ? tools.length : tools.filter((tool) => tool.category === item.id).length}</span></button>)}</div></section>
    <section className="container-wide pt-15"><div className="mb-5 flex items-center justify-between"><div><p className="eyebrow text-primary">EDITOR&apos;S DESK / 02</p><h2 className="section-heading mt-3">常用，也值得好用</h2></div><span className="hidden text-[13px] text-muted-foreground md:block">从高频任务开始，少一点绕路。</span></div><div className="grid gap-4 md:grid-cols-2"><Link href="/tools/json/" className="featured-card group bg-[#ddd9ff] text-[#262449] dark:bg-[#4a437c] dark:text-[#f4f0ff]"><span className="eyebrow">01 / DATA STUDIO</span><h3 className="mt-12 text-[30px] font-bold tracking-[-.06em] md:text-[35px]">JSON，读起来<br/>应该很轻松。</h3><span className="mt-5 inline-flex items-center gap-2 text-[13px] font-semibold">打开格式化工具 <ArrowUpRight size={16} className="transition-transform group-hover:translate-x-1 group-hover:-translate-y-1"/></span><span className="absolute -bottom-17 right-3 font-mono text-[190px] leading-none tracking-[-.2em] text-[#aea7fa]/40 dark:text-[#b1a8ff]/15" aria-hidden="true">&#123; &#125;</span></Link><Link href="/tools/qr/" className="featured-card group bg-[#dcefe9] text-[#203b34] dark:bg-[#2e594d] dark:text-[#eafff6]"><span className="eyebrow">02 / CREATIVE STUDIO</span><h3 className="mt-12 text-[30px] font-bold tracking-[-.06em] md:text-[35px]">把想分享的，<br/>变成一个方块。</h3><span className="mt-5 inline-flex items-center gap-2 text-[13px] font-semibold">打开二维码工具 <ArrowUpRight size={16} className="transition-transform group-hover:translate-x-1 group-hover:-translate-y-1"/></span><span className="absolute bottom-8 right-9 grid h-35 w-35 rotate-[-9deg] place-items-center rounded-3xl border-2 border-[#315b50]/12 bg-white/55 text-[80px] shadow-xl dark:bg-white/8" aria-hidden="true">▦</span></Link></div></section>
    <section className="container-wide pt-18"><div className="mb-5 flex items-end justify-between"><div><p className="eyebrow text-primary">ALL ESSENTIALS / 03</p><h2 className="section-heading mt-3">全部工具</h2></div><span className="text-[12px] text-muted-foreground">{filtered.length} / {tools.length} 个工具</span></div>{filtered.length ? <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{filtered.map((tool) => <ToolCard key={tool.id} tool={tool}/>)}</div> : <div className="surface-panel py-16 text-center"><p className="text-lg font-semibold">没有找到匹配的工具</p><p className="mt-2 text-sm text-muted-foreground">换个关键词，或者切回「全部工具」。</p><button type="button" className="chip-button mt-5" onClick={() => { setCategory("all"); setQuery(""); }}>查看全部工具</button></div>}</section>
  </>;
}
